### ISSUE TITLE
Update strings

### ISSUE THREAD

**Issue by M2ck** [abcdjdj/RootVerifier-APP#7]
For provide translation, thanks

**Comment by abcdjdj** [comment]
I will try to include it in the next update.

**Comment by M2ck** [comment]
Thanks, I will send a pull request when it will be done.

**Comment by abcdjdj** [comment]
I have removed all hard coded strings. Everything is placed in strings.xml. Feel free to send a pull request any time :)

**Comment by M2ck** [comment]
Ok thanks!
