### ISSUE TITLE
Permit install on external memory card

### ISSUE THREAD

**Issue by Gitoffthelawn** [abcdjdj/RootVerifier-APP#9]
Can you set the flag to allow it to be installed on an external memory card?

**Comment by abcdjdj** [comment]
Yes, I will add it in the next update.

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by abcdjdj** [comment]
[https://github.com/abcdjdj/RootVerifier-APP/commit/4fe00f27a867254b585629e784179d8c49459ab6](url)

**Comment by Gitoffthelawn** [comment]
Awesome!  I'll give it a spin.
